'use client'

import OperatorGate from './OperatorGate'

interface BioSummaryProps {
  bioSummary: string | null
  bioGeneratedAt: string | null
  bioModel: string | null
  officialName: string
  meetingCount: number
}

export default function BioSummary({
  bioSummary,
  bioGeneratedAt,
  bioModel,
  officialName,
  meetingCount,
}: BioSummaryProps) {
  if (!bioSummary) return null

  return (
    <OperatorGate>
      <section className="mb-8">
        <div className="flex items-center gap-2 mb-3">
          <h2 className="text-xl font-semibold text-slate-800">AI Summary</h2>
          <span className="text-xs bg-amber-100 text-amber-800 px-2 py-0.5 rounded font-medium">
            Operator Only
          </span>
        </div>
        <div className="bg-white rounded-lg border border-slate-200 p-4">
          <p className="text-sm text-slate-800 leading-relaxed">{bioSummary}</p>
          <hr className="my-3 border-slate-100" />
          <p className="text-xs text-slate-400 leading-relaxed">
            This summary was generated by AI based on {officialName}&apos;s voting record
            across {meetingCount} meetings. It reflects patterns in official vote data,
            not editorial judgment.
            <br />
            Data sources: City of Richmond certified meeting minutes
            {bioGeneratedAt && (
              <>
                <br />
                Last updated: {new Date(bioGeneratedAt).toLocaleDateString()}
              </>
            )}
            {bioModel && (
              <>
                <br />
                Model: {bioModel}
              </>
            )}
          </p>
        </div>
      </section>
    </OperatorGate>
  )
}
